type Paragraph @model {
    id: ID!
    article: Article @connection(name: "ArticleParagraphs")
    content: String! 
    contentType: String!
    seqNumber: Int!
    contentImage: S3Object
    contentImage_key: String
    contentImageAlt: String
    audio_key: String
    videoURL: String
}

type Expression @model 
@key(
    name: "byLabel"
    fields: ["label", "createdAt"]
    queryField: "getExpressionsByLabel"
)
{
    id: ID!
    label: String!
    contentZh: String
    createdAt: String!
    contentPinyin: String
    contentEn: String
    audio: S3Object
    audio_key: String
}

type Article @model
@key(
  name: "byStatus"
  fields: ["status", "createdAt"]
  queryField: "getArticlesByStatus"
)
@key(
  name: "bySlug"
  fields: ["slug"]
  queryField: "getArticleBySlug"
)
{
    id: ID!
    coverImage: S3Object
    coverImage_key: String
    coverImageAlt: String
    slug: String!
    titleEn: String!
    titleZh: String!
    whyYouShouldReadThisArticle: String!
    createdAt: String!
    tags: [TagArticle] @connection(name: "ArticleTag")
    vocabularies: [VocabularyArticle] @connection(name: "ArticleVocabulary")
    sourcer: String
    paragraphs: [Paragraph] @connection(name: "ArticleParagraphs")
    audioEnKey: String
    audioZhKey: String
    status: String!  
} 

type ArticleSource @model
{
    id: ID!
    name: String
}

type Vocabulary @model {
    id: ID!
    contentZh: String!
    contentEn: String!
    contentPinyin: String!
    label: String 
    audio: S3Object
    audio_key: String
    optionContent: String
    articles: [VocabularyArticle] @connection(name: "VocabularyArticle")
}

type TrendingPhrase @model @key(
  name: "byStatus"
  fields: ["status", "createdAt"]
  queryField: "getTrendingPhrasesByStatus"
){
    id: ID!
    contentZh: String!
    status: String!
    createdAt: String!
    contentPinyin: String
    audioKey: String
    description: String
}

type VocabularyArticle @model 
@key(
  name: "byParagraphId"
  fields: ["paragraphId"]
  queryField: "getVocabularyArticlesByParagraphId"
){  
    id: ID!
    article: Article @connection(name: "ArticleVocabulary", sortField: "createdAt")
    vocabulary: Vocabulary @connection(name: "VocabularyArticle")
    paragraphId: ID
    startIndex: Int
}

type Tag @model {
    id: ID!
    content: String!
    articles: [TagArticle] @connection(name: "TagArticle")
    dialogues: [TagDialogue] @connection(name: "TagDialogue")
    image: S3Object
    image_key: String
    isFeatured: Boolean
    featuredSlogan: String
    featuredImage: S3Object
    featuredImage_key: String
}

type TagArticle @model {  #for many to many relationship
    id: ID!
    article: Article @connection(name: "ArticleTag", sortField: "createdAt")
    tag: Tag @connection(name: "TagArticle")
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}

type Chapter @model {
    id: ID!
    contentZh: String
    contentPinyin: String
    contentEn: String
    audio: S3Object
    audio_key: String
    seqNumber:Int
    npcName: String
    npcAvatar: S3Object
    npcAvatar_key: String
    npcRole: String
    dialogue: Dialogue @connection(name: "DialogueChapters")
}

type Dialogue @model 
@key(
  name: "byStatus"
  fields: ["status", "createdAt"]
  queryField: "getDialoguesByStatus"
){ 
    id: ID!
    coverImage: S3Object
    coverImage_key: String
    titleZh: String
    titleEn: String
    whyYouShouldLearnThisDialogue: String    
    difficultyLevel: String
    tags: [TagDialogue] @connection(name: "DialogueTag")
    chapters: [Chapter] @connection(name: "DialogueChapters")
    status: String!
    createdAt: String!
    markAsMostPopular: Boolean 
}


type UserChapterRecording @model
@key(
    name: "findByUserChapter"
    fields: ["user_id", "chapter_id"]
    queryField: "getChapterRecordingByUserAndChapter"
)
{
    id: ID!
    user_id: String!
    chapter_id: String!
    mode: String! # SOLO or DUO
    score: Float
    score_extra: AWSJSON
}

type UserExpressionRecording @model
@key(
    name: "findByUserExpression"
    fields: ["user_id", "expression_id"]
    queryField: "getExpressionRecordingByUserAndExpression"
)
{
    id: ID!
    user_id: String!
    expression_id: String!
    score: Float
    score_extra: AWSJSON
}


type TagDialogue @model {  #for many to many relationship
    id: ID!
    dialogue: Dialogue @connection(name: "DialogueTag", sortField: "createdAt")
    tag: Tag @connection(name: "TagDialogue")
}

type Npc @model {
    id: ID!
    name: String!
    avatar: S3Object
    avatar_key: String
}


# User status table

type User @model {
    id: ID!
    username: String!
    email: String!
    deviceToken: String
    avatar: S3Object
    avatar_key: String
    goals: [String!]
    interests: [String!]
    profession: String

    completedItems: [UserItemCompleted] @connection(name: "UserItemCompleted")
    inProgressItems: [UserItemInProgress] @connection(name: "UserItemInProgress")
    savedItems: [UserItemSave] @connection(name: "UserItemSave")
    savedVocabularies: [UserVocabularySave] @connection(name: "UserVocabularySave")
}

type UserItemCompleted @model {
    id: ID!
    user: User @connection(name: "UserItemCompleted")
    itemType: String # STORY EXPRESSION TALK
    itemID: ID!
}

type UserItemInProgress @model {
    id: ID!
    user: User @connection(name: "UserItemInProgress")
    itemType: String # STORY EXPRESSION TALK
    itemID: ID!
}

type UserItemSave @model {
    id: ID!
    user: User @connection(name: "UserItemSave")
    itemType: String # STORY EXPRESSION TALK
    itemID: ID!
}

type UserVocabularySave @model {
    id: ID!
    users: User @connection(name: "UserVocabularySave")
    vocabularyID: ID!
}

