type User @model {
    id: ID!
    username: String!
    email: string!
    avatar: S3Object
    goals: [string]
    interests: [string]
    professional: string

    completedItems: [UserItemCompleted] @connection(name: "UserItemCompleted")
    inProgressItems: [UserItemInProgress] @connection(name: "UserItemInProgress")
    savedItems: [UserItemSave] @connection(name: "UserItemSave")
    savedVocabularies: [UserVocabularySave] @connection(name: "UserVocabularySave")
}

type UserItemCompleted @model {
    id: ID!
    user: User @connection(name: "UserItemCompleted")
    itemType: string # STORY EXPRESSION TALK
    itemID: ID!
}

type UserItemInProgress @model {
    id: ID!
    user: User @connection(name: "UserItemInProgress")
    itemType: string # STORY EXPRESSION TALK
    itemID: ID!
}

type UserItemSave @model {
    id: ID!
    user: User @connection(name: "UserItemSave")
    itemType: string # STORY EXPRESSION TALK
    itemID: ID!
}

type UserVocabularySave @model {
    id: ID!
    users: User @connection(name: "UserVocabularySave")
    vocabularyID: ID!
}